from pytube import YouTube
import logging

class Youtuber:
    def __init__(self, download_path ,resolution):
        self.download_path = download_path
        self.resolution = resolution
    def download_audio(self, link):
        youtubeObject = YouTube(link)
        youtubeObject = youtubeObject.streams.filter(only_audio=True).first()
        try:
            # TODO File name should be autogenerated 
            file_name = "audio_input.mp3"
            youtubeObject.download(output_path=self.download_path, filename=file_name)
        except:
            logging.fatal("Failed to download")
        logging.info(f"Download is completed successfully {file_name}")
        return file_name